name: CI
on:
  push:
    branches: [master, dev]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    env:
      RESOURCE_NAME: ${{ github.ref == 'refs/heads/master' && 'prod-api' || 'dev-api' }}
      NAMESPACE: ${{ github.ref == 'refs/heads/master' && 'gala-prod' || 'gala-dev' }}
    steps:
      - uses: actions/checkout@v2
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
      - name: Login to OKD
        run: oc login --token=${{ secrets.OKD_TOKEN }} --server=${{ secrets.OKD_SERVER }}

      - name: Change the project
        run: oc project ${{ env.NAMESPACE }}

      - name: Start the build
        run: oc start-build ${{ env.RESOURCE_NAME }} --follow

      - uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Deployment to ${{ env.RESOURCE_NAME }}*'
          commit: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          token: ${{ secrets.GITHUB_TOKEN }}
